services:
  postgres:
    image: postgres:15
    container_name: market-app
    environment:
      POSTGRES_DB: market-app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-market-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d market-app" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: market-redis
    ports:
      - "6379:6379"
    networks:
      - my-market-app
    restart: always
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  shop-app:
    build: ./shop
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - payment-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      PAYMENT_SERVICE_URL: http://payment-service:8081

  payment-service:
    container_name: payment-service
    build: ./payment-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      PAYMENT_BALANCE: 1000

volumes:
  postgres_data:
  redis_data:

networks:
  my-market-app:
    driver: bridge