server:
  port: 8085

spring:
  application:
    name: shop-app

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: shop-app
            client-secret: G7lxD1V4oAJnPFFa5OelPZlQQQ8H746W
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email

          payment:
            provider: keycloak
            client-id: shop-app
            client-secret: G7lxD1V4oAJnPFFa5OelPZlQQQ8H746W
            authorization-grant-type: client_credentials
            scope:
              - payments.read
              - payments.write

        provider:
          keycloak:
            issuer-uri:
              http://localhost:8080/realms/shop-realm

  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: spring:session

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/market-app
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/market-app
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.yourpackage: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


payment-service:
  url: http://localhost:8086
